# Generated by Django 4.1.7 on 2024-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='one_day_cake',
            field=models.BooleanField(default=False),
        ),
    ]
